// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tsc.proto

#ifndef PROTOBUF_tsc_2eproto__INCLUDED
#define PROTOBUF_tsc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)

namespace protobuf_tsc_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsUserImpl();
void InitDefaultsUser();
void InitDefaultsFollowRequestImpl();
void InitDefaultsFollowRequest();
void InitDefaultsUnfollowRequestImpl();
void InitDefaultsUnfollowRequest();
void InitDefaultsConnectRequestImpl();
void InitDefaultsConnectRequest();
void InitDefaultsFollowReplyImpl();
void InitDefaultsFollowReply();
void InitDefaultsListReplyImpl();
void InitDefaultsListReply();
void InitDefaultsPostImpl();
void InitDefaultsPost();
inline void InitDefaults() {
  InitDefaultsUser();
  InitDefaultsFollowRequest();
  InitDefaultsUnfollowRequest();
  InitDefaultsConnectRequest();
  InitDefaultsFollowReply();
  InitDefaultsListReply();
  InitDefaultsPost();
}
}  // namespace protobuf_tsc_2eproto
namespace tsc {
class ConnectRequest;
class ConnectRequestDefaultTypeInternal;
extern ConnectRequestDefaultTypeInternal _ConnectRequest_default_instance_;
class FollowReply;
class FollowReplyDefaultTypeInternal;
extern FollowReplyDefaultTypeInternal _FollowReply_default_instance_;
class FollowRequest;
class FollowRequestDefaultTypeInternal;
extern FollowRequestDefaultTypeInternal _FollowRequest_default_instance_;
class ListReply;
class ListReplyDefaultTypeInternal;
extern ListReplyDefaultTypeInternal _ListReply_default_instance_;
class Post;
class PostDefaultTypeInternal;
extern PostDefaultTypeInternal _Post_default_instance_;
class UnfollowRequest;
class UnfollowRequestDefaultTypeInternal;
extern UnfollowRequestDefaultTypeInternal _UnfollowRequest_default_instance_;
class User;
class UserDefaultTypeInternal;
extern UserDefaultTypeInternal _User_default_instance_;
}  // namespace tsc
namespace tsc {

// ===================================================================

class User : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tsc.User) */ {
 public:
  User();
  virtual ~User();

  User(const User& from);

  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  User(User&& from) noexcept
    : User() {
    *this = ::std::move(from);
  }

  inline User& operator=(User&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const User& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const User* internal_default_instance() {
    return reinterpret_cast<const User*>(
               &_User_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(User* other);
  friend void swap(User& a, User& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline User* New() const PROTOBUF_FINAL { return New(NULL); }

  User* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const User& from);
  void MergeFrom(const User& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(User* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:tsc.User)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend struct ::protobuf_tsc_2eproto::TableStruct;
  friend void ::protobuf_tsc_2eproto::InitDefaultsUserImpl();
};
// -------------------------------------------------------------------

class FollowRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tsc.FollowRequest) */ {
 public:
  FollowRequest();
  virtual ~FollowRequest();

  FollowRequest(const FollowRequest& from);

  inline FollowRequest& operator=(const FollowRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FollowRequest(FollowRequest&& from) noexcept
    : FollowRequest() {
    *this = ::std::move(from);
  }

  inline FollowRequest& operator=(FollowRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FollowRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FollowRequest* internal_default_instance() {
    return reinterpret_cast<const FollowRequest*>(
               &_FollowRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(FollowRequest* other);
  friend void swap(FollowRequest& a, FollowRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FollowRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  FollowRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FollowRequest& from);
  void MergeFrom(const FollowRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FollowRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user1 = 1;
  void clear_user1();
  static const int kUser1FieldNumber = 1;
  const ::std::string& user1() const;
  void set_user1(const ::std::string& value);
  #if LANG_CXX11
  void set_user1(::std::string&& value);
  #endif
  void set_user1(const char* value);
  void set_user1(const char* value, size_t size);
  ::std::string* mutable_user1();
  ::std::string* release_user1();
  void set_allocated_user1(::std::string* user1);

  // string user2 = 2;
  void clear_user2();
  static const int kUser2FieldNumber = 2;
  const ::std::string& user2() const;
  void set_user2(const ::std::string& value);
  #if LANG_CXX11
  void set_user2(::std::string&& value);
  #endif
  void set_user2(const char* value);
  void set_user2(const char* value, size_t size);
  ::std::string* mutable_user2();
  ::std::string* release_user2();
  void set_allocated_user2(::std::string* user2);

  // @@protoc_insertion_point(class_scope:tsc.FollowRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user1_;
  ::google::protobuf::internal::ArenaStringPtr user2_;
  mutable int _cached_size_;
  friend struct ::protobuf_tsc_2eproto::TableStruct;
  friend void ::protobuf_tsc_2eproto::InitDefaultsFollowRequestImpl();
};
// -------------------------------------------------------------------

class UnfollowRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tsc.UnfollowRequest) */ {
 public:
  UnfollowRequest();
  virtual ~UnfollowRequest();

  UnfollowRequest(const UnfollowRequest& from);

  inline UnfollowRequest& operator=(const UnfollowRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UnfollowRequest(UnfollowRequest&& from) noexcept
    : UnfollowRequest() {
    *this = ::std::move(from);
  }

  inline UnfollowRequest& operator=(UnfollowRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UnfollowRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UnfollowRequest* internal_default_instance() {
    return reinterpret_cast<const UnfollowRequest*>(
               &_UnfollowRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(UnfollowRequest* other);
  friend void swap(UnfollowRequest& a, UnfollowRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UnfollowRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UnfollowRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UnfollowRequest& from);
  void MergeFrom(const UnfollowRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UnfollowRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user1 = 1;
  void clear_user1();
  static const int kUser1FieldNumber = 1;
  const ::std::string& user1() const;
  void set_user1(const ::std::string& value);
  #if LANG_CXX11
  void set_user1(::std::string&& value);
  #endif
  void set_user1(const char* value);
  void set_user1(const char* value, size_t size);
  ::std::string* mutable_user1();
  ::std::string* release_user1();
  void set_allocated_user1(::std::string* user1);

  // string user2 = 2;
  void clear_user2();
  static const int kUser2FieldNumber = 2;
  const ::std::string& user2() const;
  void set_user2(const ::std::string& value);
  #if LANG_CXX11
  void set_user2(::std::string&& value);
  #endif
  void set_user2(const char* value);
  void set_user2(const char* value, size_t size);
  ::std::string* mutable_user2();
  ::std::string* release_user2();
  void set_allocated_user2(::std::string* user2);

  // @@protoc_insertion_point(class_scope:tsc.UnfollowRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user1_;
  ::google::protobuf::internal::ArenaStringPtr user2_;
  mutable int _cached_size_;
  friend struct ::protobuf_tsc_2eproto::TableStruct;
  friend void ::protobuf_tsc_2eproto::InitDefaultsUnfollowRequestImpl();
};
// -------------------------------------------------------------------

class ConnectRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tsc.ConnectRequest) */ {
 public:
  ConnectRequest();
  virtual ~ConnectRequest();

  ConnectRequest(const ConnectRequest& from);

  inline ConnectRequest& operator=(const ConnectRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectRequest(ConnectRequest&& from) noexcept
    : ConnectRequest() {
    *this = ::std::move(from);
  }

  inline ConnectRequest& operator=(ConnectRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectRequest* internal_default_instance() {
    return reinterpret_cast<const ConnectRequest*>(
               &_ConnectRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ConnectRequest* other);
  friend void swap(ConnectRequest& a, ConnectRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ConnectRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConnectRequest& from);
  void MergeFrom(const ConnectRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConnectRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user1 = 1;
  void clear_user1();
  static const int kUser1FieldNumber = 1;
  const ::std::string& user1() const;
  void set_user1(const ::std::string& value);
  #if LANG_CXX11
  void set_user1(::std::string&& value);
  #endif
  void set_user1(const char* value);
  void set_user1(const char* value, size_t size);
  ::std::string* mutable_user1();
  ::std::string* release_user1();
  void set_allocated_user1(::std::string* user1);

  // @@protoc_insertion_point(class_scope:tsc.ConnectRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user1_;
  mutable int _cached_size_;
  friend struct ::protobuf_tsc_2eproto::TableStruct;
  friend void ::protobuf_tsc_2eproto::InitDefaultsConnectRequestImpl();
};
// -------------------------------------------------------------------

class FollowReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tsc.FollowReply) */ {
 public:
  FollowReply();
  virtual ~FollowReply();

  FollowReply(const FollowReply& from);

  inline FollowReply& operator=(const FollowReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FollowReply(FollowReply&& from) noexcept
    : FollowReply() {
    *this = ::std::move(from);
  }

  inline FollowReply& operator=(FollowReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FollowReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FollowReply* internal_default_instance() {
    return reinterpret_cast<const FollowReply*>(
               &_FollowReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(FollowReply* other);
  friend void swap(FollowReply& a, FollowReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FollowReply* New() const PROTOBUF_FINAL { return New(NULL); }

  FollowReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FollowReply& from);
  void MergeFrom(const FollowReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FollowReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  ::google::protobuf::int32 message() const;
  void set_message(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tsc.FollowReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 message_;
  mutable int _cached_size_;
  friend struct ::protobuf_tsc_2eproto::TableStruct;
  friend void ::protobuf_tsc_2eproto::InitDefaultsFollowReplyImpl();
};
// -------------------------------------------------------------------

class ListReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tsc.ListReply) */ {
 public:
  ListReply();
  virtual ~ListReply();

  ListReply(const ListReply& from);

  inline ListReply& operator=(const ListReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ListReply(ListReply&& from) noexcept
    : ListReply() {
    *this = ::std::move(from);
  }

  inline ListReply& operator=(ListReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ListReply* internal_default_instance() {
    return reinterpret_cast<const ListReply*>(
               &_ListReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ListReply* other);
  friend void swap(ListReply& a, ListReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ListReply* New() const PROTOBUF_FINAL { return New(NULL); }

  ListReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ListReply& from);
  void MergeFrom(const ListReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ListReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string users = 1;
  int users_size() const;
  void clear_users();
  static const int kUsersFieldNumber = 1;
  const ::std::string& users(int index) const;
  ::std::string* mutable_users(int index);
  void set_users(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_users(int index, ::std::string&& value);
  #endif
  void set_users(int index, const char* value);
  void set_users(int index, const char* value, size_t size);
  ::std::string* add_users();
  void add_users(const ::std::string& value);
  #if LANG_CXX11
  void add_users(::std::string&& value);
  #endif
  void add_users(const char* value);
  void add_users(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& users() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_users();

  // repeated string allusers = 2;
  int allusers_size() const;
  void clear_allusers();
  static const int kAllusersFieldNumber = 2;
  const ::std::string& allusers(int index) const;
  ::std::string* mutable_allusers(int index);
  void set_allusers(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_allusers(int index, ::std::string&& value);
  #endif
  void set_allusers(int index, const char* value);
  void set_allusers(int index, const char* value, size_t size);
  ::std::string* add_allusers();
  void add_allusers(const ::std::string& value);
  #if LANG_CXX11
  void add_allusers(::std::string&& value);
  #endif
  void add_allusers(const char* value);
  void add_allusers(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& allusers() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_allusers();

  // @@protoc_insertion_point(class_scope:tsc.ListReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> users_;
  ::google::protobuf::RepeatedPtrField< ::std::string> allusers_;
  mutable int _cached_size_;
  friend struct ::protobuf_tsc_2eproto::TableStruct;
  friend void ::protobuf_tsc_2eproto::InitDefaultsListReplyImpl();
};
// -------------------------------------------------------------------

class Post : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tsc.Post) */ {
 public:
  Post();
  virtual ~Post();

  Post(const Post& from);

  inline Post& operator=(const Post& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Post(Post&& from) noexcept
    : Post() {
    *this = ::std::move(from);
  }

  inline Post& operator=(Post&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Post& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Post* internal_default_instance() {
    return reinterpret_cast<const Post*>(
               &_Post_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(Post* other);
  friend void swap(Post& a, Post& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Post* New() const PROTOBUF_FINAL { return New(NULL); }

  Post* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Post& from);
  void MergeFrom(const Post& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Post* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string content = 1;
  void clear_content();
  static const int kContentFieldNumber = 1;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // string auth = 2;
  void clear_auth();
  static const int kAuthFieldNumber = 2;
  const ::std::string& auth() const;
  void set_auth(const ::std::string& value);
  #if LANG_CXX11
  void set_auth(::std::string&& value);
  #endif
  void set_auth(const char* value);
  void set_auth(const char* value, size_t size);
  ::std::string* mutable_auth();
  ::std::string* release_auth();
  void set_allocated_auth(::std::string* auth);

  // @@protoc_insertion_point(class_scope:tsc.Post)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  ::google::protobuf::internal::ArenaStringPtr auth_;
  mutable int _cached_size_;
  friend struct ::protobuf_tsc_2eproto::TableStruct;
  friend void ::protobuf_tsc_2eproto::InitDefaultsPostImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// User

// string name = 1;
inline void User::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& User::name() const {
  // @@protoc_insertion_point(field_get:tsc.User.name)
  return name_.GetNoArena();
}
inline void User::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.User.name)
}
#if LANG_CXX11
inline void User::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.User.name)
}
#endif
inline void User::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.User.name)
}
inline void User::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.User.name)
}
inline ::std::string* User::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tsc.User.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* User::release_name() {
  // @@protoc_insertion_point(field_release:tsc.User.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void User::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tsc.User.name)
}

// -------------------------------------------------------------------

// FollowRequest

// string user1 = 1;
inline void FollowRequest::clear_user1() {
  user1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FollowRequest::user1() const {
  // @@protoc_insertion_point(field_get:tsc.FollowRequest.user1)
  return user1_.GetNoArena();
}
inline void FollowRequest::set_user1(const ::std::string& value) {
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.FollowRequest.user1)
}
#if LANG_CXX11
inline void FollowRequest::set_user1(::std::string&& value) {
  
  user1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.FollowRequest.user1)
}
#endif
inline void FollowRequest::set_user1(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.FollowRequest.user1)
}
inline void FollowRequest::set_user1(const char* value, size_t size) {
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.FollowRequest.user1)
}
inline ::std::string* FollowRequest::mutable_user1() {
  
  // @@protoc_insertion_point(field_mutable:tsc.FollowRequest.user1)
  return user1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FollowRequest::release_user1() {
  // @@protoc_insertion_point(field_release:tsc.FollowRequest.user1)
  
  return user1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FollowRequest::set_allocated_user1(::std::string* user1) {
  if (user1 != NULL) {
    
  } else {
    
  }
  user1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user1);
  // @@protoc_insertion_point(field_set_allocated:tsc.FollowRequest.user1)
}

// string user2 = 2;
inline void FollowRequest::clear_user2() {
  user2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FollowRequest::user2() const {
  // @@protoc_insertion_point(field_get:tsc.FollowRequest.user2)
  return user2_.GetNoArena();
}
inline void FollowRequest::set_user2(const ::std::string& value) {
  
  user2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.FollowRequest.user2)
}
#if LANG_CXX11
inline void FollowRequest::set_user2(::std::string&& value) {
  
  user2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.FollowRequest.user2)
}
#endif
inline void FollowRequest::set_user2(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.FollowRequest.user2)
}
inline void FollowRequest::set_user2(const char* value, size_t size) {
  
  user2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.FollowRequest.user2)
}
inline ::std::string* FollowRequest::mutable_user2() {
  
  // @@protoc_insertion_point(field_mutable:tsc.FollowRequest.user2)
  return user2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FollowRequest::release_user2() {
  // @@protoc_insertion_point(field_release:tsc.FollowRequest.user2)
  
  return user2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FollowRequest::set_allocated_user2(::std::string* user2) {
  if (user2 != NULL) {
    
  } else {
    
  }
  user2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user2);
  // @@protoc_insertion_point(field_set_allocated:tsc.FollowRequest.user2)
}

// -------------------------------------------------------------------

// UnfollowRequest

// string user1 = 1;
inline void UnfollowRequest::clear_user1() {
  user1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UnfollowRequest::user1() const {
  // @@protoc_insertion_point(field_get:tsc.UnfollowRequest.user1)
  return user1_.GetNoArena();
}
inline void UnfollowRequest::set_user1(const ::std::string& value) {
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.UnfollowRequest.user1)
}
#if LANG_CXX11
inline void UnfollowRequest::set_user1(::std::string&& value) {
  
  user1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.UnfollowRequest.user1)
}
#endif
inline void UnfollowRequest::set_user1(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.UnfollowRequest.user1)
}
inline void UnfollowRequest::set_user1(const char* value, size_t size) {
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.UnfollowRequest.user1)
}
inline ::std::string* UnfollowRequest::mutable_user1() {
  
  // @@protoc_insertion_point(field_mutable:tsc.UnfollowRequest.user1)
  return user1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UnfollowRequest::release_user1() {
  // @@protoc_insertion_point(field_release:tsc.UnfollowRequest.user1)
  
  return user1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UnfollowRequest::set_allocated_user1(::std::string* user1) {
  if (user1 != NULL) {
    
  } else {
    
  }
  user1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user1);
  // @@protoc_insertion_point(field_set_allocated:tsc.UnfollowRequest.user1)
}

// string user2 = 2;
inline void UnfollowRequest::clear_user2() {
  user2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UnfollowRequest::user2() const {
  // @@protoc_insertion_point(field_get:tsc.UnfollowRequest.user2)
  return user2_.GetNoArena();
}
inline void UnfollowRequest::set_user2(const ::std::string& value) {
  
  user2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.UnfollowRequest.user2)
}
#if LANG_CXX11
inline void UnfollowRequest::set_user2(::std::string&& value) {
  
  user2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.UnfollowRequest.user2)
}
#endif
inline void UnfollowRequest::set_user2(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.UnfollowRequest.user2)
}
inline void UnfollowRequest::set_user2(const char* value, size_t size) {
  
  user2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.UnfollowRequest.user2)
}
inline ::std::string* UnfollowRequest::mutable_user2() {
  
  // @@protoc_insertion_point(field_mutable:tsc.UnfollowRequest.user2)
  return user2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UnfollowRequest::release_user2() {
  // @@protoc_insertion_point(field_release:tsc.UnfollowRequest.user2)
  
  return user2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UnfollowRequest::set_allocated_user2(::std::string* user2) {
  if (user2 != NULL) {
    
  } else {
    
  }
  user2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user2);
  // @@protoc_insertion_point(field_set_allocated:tsc.UnfollowRequest.user2)
}

// -------------------------------------------------------------------

// ConnectRequest

// string user1 = 1;
inline void ConnectRequest::clear_user1() {
  user1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectRequest::user1() const {
  // @@protoc_insertion_point(field_get:tsc.ConnectRequest.user1)
  return user1_.GetNoArena();
}
inline void ConnectRequest::set_user1(const ::std::string& value) {
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.ConnectRequest.user1)
}
#if LANG_CXX11
inline void ConnectRequest::set_user1(::std::string&& value) {
  
  user1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.ConnectRequest.user1)
}
#endif
inline void ConnectRequest::set_user1(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.ConnectRequest.user1)
}
inline void ConnectRequest::set_user1(const char* value, size_t size) {
  
  user1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.ConnectRequest.user1)
}
inline ::std::string* ConnectRequest::mutable_user1() {
  
  // @@protoc_insertion_point(field_mutable:tsc.ConnectRequest.user1)
  return user1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectRequest::release_user1() {
  // @@protoc_insertion_point(field_release:tsc.ConnectRequest.user1)
  
  return user1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectRequest::set_allocated_user1(::std::string* user1) {
  if (user1 != NULL) {
    
  } else {
    
  }
  user1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user1);
  // @@protoc_insertion_point(field_set_allocated:tsc.ConnectRequest.user1)
}

// -------------------------------------------------------------------

// FollowReply

// int32 message = 1;
inline void FollowReply::clear_message() {
  message_ = 0;
}
inline ::google::protobuf::int32 FollowReply::message() const {
  // @@protoc_insertion_point(field_get:tsc.FollowReply.message)
  return message_;
}
inline void FollowReply::set_message(::google::protobuf::int32 value) {
  
  message_ = value;
  // @@protoc_insertion_point(field_set:tsc.FollowReply.message)
}

// -------------------------------------------------------------------

// ListReply

// repeated string users = 1;
inline int ListReply::users_size() const {
  return users_.size();
}
inline void ListReply::clear_users() {
  users_.Clear();
}
inline const ::std::string& ListReply::users(int index) const {
  // @@protoc_insertion_point(field_get:tsc.ListReply.users)
  return users_.Get(index);
}
inline ::std::string* ListReply::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:tsc.ListReply.users)
  return users_.Mutable(index);
}
inline void ListReply::set_users(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tsc.ListReply.users)
  users_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ListReply::set_users(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:tsc.ListReply.users)
  users_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ListReply::set_users(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  users_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tsc.ListReply.users)
}
inline void ListReply::set_users(int index, const char* value, size_t size) {
  users_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tsc.ListReply.users)
}
inline ::std::string* ListReply::add_users() {
  // @@protoc_insertion_point(field_add_mutable:tsc.ListReply.users)
  return users_.Add();
}
inline void ListReply::add_users(const ::std::string& value) {
  users_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tsc.ListReply.users)
}
#if LANG_CXX11
inline void ListReply::add_users(::std::string&& value) {
  users_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tsc.ListReply.users)
}
#endif
inline void ListReply::add_users(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  users_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tsc.ListReply.users)
}
inline void ListReply::add_users(const char* value, size_t size) {
  users_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tsc.ListReply.users)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListReply::users() const {
  // @@protoc_insertion_point(field_list:tsc.ListReply.users)
  return users_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ListReply::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:tsc.ListReply.users)
  return &users_;
}

// repeated string allusers = 2;
inline int ListReply::allusers_size() const {
  return allusers_.size();
}
inline void ListReply::clear_allusers() {
  allusers_.Clear();
}
inline const ::std::string& ListReply::allusers(int index) const {
  // @@protoc_insertion_point(field_get:tsc.ListReply.allusers)
  return allusers_.Get(index);
}
inline ::std::string* ListReply::mutable_allusers(int index) {
  // @@protoc_insertion_point(field_mutable:tsc.ListReply.allusers)
  return allusers_.Mutable(index);
}
inline void ListReply::set_allusers(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tsc.ListReply.allusers)
  allusers_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ListReply::set_allusers(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:tsc.ListReply.allusers)
  allusers_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ListReply::set_allusers(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  allusers_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tsc.ListReply.allusers)
}
inline void ListReply::set_allusers(int index, const char* value, size_t size) {
  allusers_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tsc.ListReply.allusers)
}
inline ::std::string* ListReply::add_allusers() {
  // @@protoc_insertion_point(field_add_mutable:tsc.ListReply.allusers)
  return allusers_.Add();
}
inline void ListReply::add_allusers(const ::std::string& value) {
  allusers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tsc.ListReply.allusers)
}
#if LANG_CXX11
inline void ListReply::add_allusers(::std::string&& value) {
  allusers_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tsc.ListReply.allusers)
}
#endif
inline void ListReply::add_allusers(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  allusers_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tsc.ListReply.allusers)
}
inline void ListReply::add_allusers(const char* value, size_t size) {
  allusers_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tsc.ListReply.allusers)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ListReply::allusers() const {
  // @@protoc_insertion_point(field_list:tsc.ListReply.allusers)
  return allusers_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ListReply::mutable_allusers() {
  // @@protoc_insertion_point(field_mutable_list:tsc.ListReply.allusers)
  return &allusers_;
}

// -------------------------------------------------------------------

// Post

// string content = 1;
inline void Post::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Post::content() const {
  // @@protoc_insertion_point(field_get:tsc.Post.content)
  return content_.GetNoArena();
}
inline void Post::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.Post.content)
}
#if LANG_CXX11
inline void Post::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.Post.content)
}
#endif
inline void Post::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.Post.content)
}
inline void Post::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.Post.content)
}
inline ::std::string* Post::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:tsc.Post.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Post::release_content() {
  // @@protoc_insertion_point(field_release:tsc.Post.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Post::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:tsc.Post.content)
}

// string auth = 2;
inline void Post::clear_auth() {
  auth_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Post::auth() const {
  // @@protoc_insertion_point(field_get:tsc.Post.auth)
  return auth_.GetNoArena();
}
inline void Post::set_auth(const ::std::string& value) {
  
  auth_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tsc.Post.auth)
}
#if LANG_CXX11
inline void Post::set_auth(::std::string&& value) {
  
  auth_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tsc.Post.auth)
}
#endif
inline void Post::set_auth(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  auth_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tsc.Post.auth)
}
inline void Post::set_auth(const char* value, size_t size) {
  
  auth_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tsc.Post.auth)
}
inline ::std::string* Post::mutable_auth() {
  
  // @@protoc_insertion_point(field_mutable:tsc.Post.auth)
  return auth_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Post::release_auth() {
  // @@protoc_insertion_point(field_release:tsc.Post.auth)
  
  return auth_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Post::set_allocated_auth(::std::string* auth) {
  if (auth != NULL) {
    
  } else {
    
  }
  auth_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), auth);
  // @@protoc_insertion_point(field_set_allocated:tsc.Post.auth)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tsc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tsc_2eproto__INCLUDED
